### ISSUE TITLE
External SD support

### ISSUE THREAD

**Issue by Uwe-B** [JuanJakobo/Pocketbook-ZIM-Reader#1]
What a surprise, finally a working ZIM reader for PB devices. I tested it with a PB740 and it worked with smaller ZIM files! Since we can't use older ZIM files and splitted ZIM files (xapian index error). I was hoping to get a Wikipedia zim running from SD. Tried it with some zim on an SD and Pocketbook-ZIM-Reader does not include SD cards in it search patch (/mnt/ext2). Could you please change that.

**Comment by JuanJakobo** [comment]
Hey, that sounds reasonable. I will look into it once I got the time.

**Comment by Uwe-B** [comment]
I did a test with a hexedited path: just replacing /mnt/ext1 with /mnt/ext2 and it was working.
The main problem though is, that pocketbook is just supporting fat32 formated disks (I tried everything else even ext2-4), so no zim files bigger than 4GB are supported. Splitting them doesn't work either, since the index with the bigger wikipedia dumps are at the end of the file and can't be splitted and are bigger than 4GB mostly. It is a pity but one I see no possibility to solve since the new libzim does need those indexed zim files afaik.

**Comment by JuanJakobo** [comment]
ok, I also have no further idea how to solve this and would have done just the same as you. (changing the path)
I did this project just to play around as my Pocketbook does not support any SD-Cards and therefore the storage of mine is very limited and most ZIMs are rather huge...
